### ISSUE TITLE
Incomplete options and defaults in prompts

### ISSUE THREAD

**Issue by juanruitina** [canonical/prompting-client#82]
I noticed the options shown in the prompts do not match the ones I provided.

For instance, for access to the home folder, there are no options initially, meaning we give the access to the requested folder only. 

<img width="576" alt="Screenshot 2024-08-29 at 13 48 31" src="https://github.com/user-attachments/assets/82c39b4d-d7ea-41fa-bd0c-e462258fb400">

Under "More options", there should be "Everything in the home folder", "The requested folder only" and "Custom path".

<img width="576" alt="Screenshot 2024-08-29 at 13 48 44" src="https://github.com/user-attachments/assets/7c5a8645-3fcd-4d99-ac31-c38dbee1be4e">

"Custom path" should never be visible in any prompt unless the user clicks on "More options".

Similarly, when getting access to a folder right under the home folder, the options don't match the designs. For instance, for the Downloads folder, he initial options should be "Everything in the Downloads folder" and "The requested folder only".

<img width="617" alt="Screenshot 2024-08-29 at 13 21 45" src="https://github.com/user-attachments/assets/7719196c-7bb7-435d-9fa0-29265a453c28">

And under "More options", options should be "Everything in the Home folder", "Everything in the Downloads folder", "The requested folder only" and "Custom path". 

![Screenshot 2024-08-29 at 15 06 06](https://github.com/user-attachments/assets/a76dcfa3-4089-4ce7-b1da-e65c146f8d5a)

The default option should be "Everything in the Downloads folder", not "The requested folder only".

@local-optimum and @olivercalder have also been sharing similar issues [on Mattermost](https://chat.canonical.com/canonical/pl/1i3cd11793n33dzip4wfh8rxih).

I think we should just make sure the options match the logic with the [Figma designs](https://www.figma.com/design/10xVr0m8efJh043Ff6SY4G/24.10-AppArmor-prompting?node-id=2280-2220&node-type=SECTION&t=ELFB15HjmUseAIPc-0) and [board](https://www.figma.com/board/1DIGbaCf4ZjTcShYjLiAIi/24.10-AppArmor-prompting---MVP-logic?node-id=0-1&node-type=CANVAS&t=N40Iq1kuqdiTGf7s-0), I provided designs for every variant.

(I left some more feedback here: https://github.com/canonical/prompting-client/issues/85)

**Comment by sminez** [comment]
I've raised several Jira issues to cover the bugs and changes requested here:
- https://warthogs.atlassian.net/browse/UDENG-4402 covers the UI fixes and regression testing around them
- https://warthogs.atlassian.net/browse/UDENG-4403 covers the "about this app" section being broken (this is a regression following the move to using GRPC to communicate between the client and the UI we suspect)
- https://warthogs.atlassian.net/browse/UDENG-4407 covers modifying the Rust client to serve the updated options in the Figma design

As we discussed on our call yesterday, can any future changes to the Figma designs please also be accompanied with either a corresponding GitHub issue or (ideally) Jira issue detailing the requested changes you need us to make. The updates to the options per prompt variant were not communicated to myself or @d-loose which is why the implementation (and [Rust client testing](https://github.com/canonical/prompting-client/blob/main/prompting-client/src/snapd_client/interfaces/home.rs#L587)) still match the updated design from the end of July as implemented in [this commit](https://github.com/canonical/prompting-client/commit/4111bbba8b651a85e72ad91c54c7f6050237fb66). Updating the client to serve the new options is relatively quick to do but we need to know when changes have been requested.

**Comment by juanruitina** [comment]
> As we discussed on our call yesterday, can any future changes to the Figma designs please also be accompanied with either a corresponding GitHub issue or (ideally) Jira issue detailing the requested changes you need us to make.

Absolutely. I communicated changes informally and I see how that's a problem when keeping track of them, particularly given the circumstances these past weeks.
